language: cpp
compiler:
  - gcc
  - clang

before_script:
  mkdir build
  cd build
  cmake ..

script:
    - make
    - cat ./multi_download.log

branches:
  only:
    - master
notifications:
  recipients:
    - omegacoleman@gmail.com
  email:
    on_success: change
    on_failure: always
